### ISSUE TITLE
proposal: use lockfiles instead of shrinkwrap

### ISSUE THREAD

**Issue by DanielRuf** [znck/vuepack#2]
**Describe the solution you'd like**
I would like to see the usage of normal lockfiles (npm 5 introduced them and we can update npm on CI).

**Describe alternatives you've considered**
yarn or package-lock

**Comment by znck** [comment]
This project is using https://pnpm.js.org/ (A fast, disk space efficient package manager).

It is alternative to yarn and npm. Checkout https://github.com/pnpm.

P.S.: Lock files (`yarn.lock` for yarn, `package-lock.json` for npm or `shrinkwrap.yaml` for pnpm) does not effect the users of the package.

**Comment by DanielRuf** [comment]
Well, another package manager. Why is it needed and what issues does it solve that npm 5+ and yarn can not?

**Comment by znck** [comment]
> pnpm uses hard links and symlinks to save one version of a module only ever once on a disk. When using npm or Yarn for example, if you have 100 projects using the same version of lodash, you will have 100 copies of lodash on disk. With pnpm, lodash will be saved in a single place on the disk and a hard link will put it into the node_modules where it should be installed.

And also https://www.kochan.io/nodejs/pnpms-strictness-helps-to-avoid-silly-bugs.html

**Comment by DanielRuf** [comment]
Thanks for the helpful information. 👍 Will evaluate it but I think it is not yet used by enough developers and I see some issues which can be blockers for our (internal) enterprise projects at work. 😨 

Nevertheless great solution, let's see how npm and yarn will evolve.

**Comment by znck** [comment]
It's true. You run into issues when using pnpm.js and commonly when using babel. I am just giving it a try. If I am stuck, I can always go back to yarn or npm.

Thanks for starting the conversation.
